// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AccountExists(ctx context.Context, arg AccountExistsParams) (bool, error)
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) error
	BlockSession(ctx context.Context, id pgtype.UUID) error
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteEntry(ctx context.Context, id int64) error
	DeleteTransfer(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	GetAccountFromOwner(ctx context.Context, arg GetAccountFromOwnerParams) (Account, error)
	GetActiveSessions(ctx context.Context, arg GetActiveSessionsParams) ([]int32, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetSession(ctx context.Context, id pgtype.UUID) (Session, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	GetTransferFromAccount(ctx context.Context, arg GetTransferFromAccountParams) ([]Transfer, error)
	GetTransferFromAndToAccount(ctx context.Context, arg GetTransferFromAndToAccountParams) ([]Transfer, error)
	GetTransferToAccount(ctx context.Context, arg GetTransferToAccountParams) ([]Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListEntriesForAccount(ctx context.Context, arg ListEntriesForAccountParams) ([]Entry, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	SubtractAccountBalance(ctx context.Context, arg SubtractAccountBalanceParams) error
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error
	UpdateEntryAmount(ctx context.Context, arg UpdateEntryAmountParams) error
	UpdateTransferAmount(ctx context.Context, arg UpdateTransferAmountParams) error
	UserExists(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
