// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) error
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteEntry(ctx context.Context, id int64) error
	DeleteTransfer(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	GetTransferFromAccount(ctx context.Context, arg GetTransferFromAccountParams) ([]Transfer, error)
	GetTransferFromAndToAccount(ctx context.Context, arg GetTransferFromAndToAccountParams) ([]Transfer, error)
	GetTransferToAccount(ctx context.Context, arg GetTransferToAccountParams) ([]Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListEntriesForAccount(ctx context.Context, arg ListEntriesForAccountParams) ([]Entry, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	SubtractAccountBalance(ctx context.Context, arg SubtractAccountBalanceParams) error
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error
	UpdateEntryAmount(ctx context.Context, arg UpdateEntryAmountParams) error
	UpdateTransferAmount(ctx context.Context, arg UpdateTransferAmountParams) error
}

var _ Querier = (*Queries)(nil)
