// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blockSession = `-- name: BlockSession :exec
UPDATE sessions
SET is_blocked = TRUE
WHERE id = $1
RETURNING id, username, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at
`

func (q *Queries) BlockSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, blockSession, id)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
  id, username, refresh_token, user_agent, client_ip, expires_at
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, username, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at
`

type CreateSessionParams struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	RefreshToken string             `json:"refresh_token"`
	UserAgent    string             `json:"user_agent"`
	ClientIp     string             `json:"client_ip"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.Username,
		arg.RefreshToken,
		arg.UserAgent,
		arg.ClientIp,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSessions = `-- name: GetActiveSessions :many
SELECT 1
FROM sessions
WHERE id = $1
  AND username = $2
  AND refresh_token = $3
  AND is_blocked = FALSE
  AND expires_at > NOW()
  LIMIT 1
`

type GetActiveSessionsParams struct {
	ID           pgtype.UUID `json:"id"`
	Username     string      `json:"username"`
	RefreshToken string      `json:"refresh_token"`
}

func (q *Queries) GetActiveSessions(ctx context.Context, arg GetActiveSessionsParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, getActiveSessions, arg.ID, arg.Username, arg.RefreshToken)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var column_1 int32
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT id, username, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at FROM sessions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
