// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username, full_name, email, password_hash
) VALUES (
  $1, $2, $3, $4
)
RETURNING username, password_hash, full_name, email, password_changed_at, craeted_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	FullName     string `json:"full_name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.FullName,
		arg.Email,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CraetedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT username, password_hash, full_name, email, password_changed_at, craeted_at FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Email,
		&i.PasswordChangedAt,
		&i.CraetedAt,
	)
	return i, err
}
