syntax = "proto3";

package pb;

option go_package = "example.com/pb";

import "google/api/annotations.proto";
import "rpc_create_user.proto";
import "rpc_get_user.proto";
import "rpc_login_user.proto";
import "google/protobuf/empty.proto";

// User service definition
service UserService {
  rpc CreateUser(CreateUserRequest) returns (CreateUserResponse) {
    option (google.api.http) = {
      post: "/v1/create_user"
      body: "*"
    };
  };
  rpc GetUser(google.protobuf.Empty) returns (GetUserResponse) {
    option (google.api.http) = {
      get: "/v1/get_user"
    };
  };  
  rpc LoginUser(LoginUserRequest) returns (LoginUserResponse) {
    option (google.api.http) = {
      post: "/v1/login_user"
      body: "*"
    };
  };
}